config/routes.rb
Mtp::Application.routes.draw do
  resources :people

  resources :organizations do
    collection do
      get :get_children
    end
    
    member do
      get :set_current
    end
  end
  
  resources :offices do
    collection do
      get :get_children
      get :get_roots
    end
  end
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"

  root :to => "sessions#new"
  
  resources :users
  resources :sessions

end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :birth_date, :first_name, :last_name, :middle_name, :office_id, :organization_id, :cfo_id, :people_offices_attributes, :addresses_attributes, :phone_numbers_attributes, :fb_profile
  
  belongs_to :organization
  belongs_to :cfo
  has_many :people_offices, :dependent => :destroy
  has_many :offices, :through => :people_offices
  has_many :addresses, :dependent => :destroy
  has_many :phone_numbers, :dependent => :destroy
  accepts_nested_attributes_for :addresses, :allow_destroy => true
  accepts_nested_attributes_for :phone_numbers, :allow_destroy => true
  
  accepts_nested_attributes_for :people_offices, :allow_destroy => true
  
  validates_presence_of :first_name, :last_name, :organization, message: "can't be blank"
  
  def name
    [first_name, middle_name, last_name].collect(&:to_s).join(' ')
  end
  
  def office_names
    names = []
    offices.each do |o|
      names += [get_names_of_self_and_parents(o).reverse.join(" - ")]
    end
    names
  end
  
  def organization_names(up_to_org)
    names = []
    get_names_of_self_and_parents(organization, up_to_org).reverse.join(" - ")
  end
  
  def delete_offices
    people_offices.collect(&:destroy)
  end
  
  def delete_addresses
    addresses.collect(&:destroy)
  end
  
  def delete_phone_numbers
    phone_numbers.collect(&:destroy)
  end
  
  def fb_username
    fb_profile.nil? ? "" : fb_profile.split('/').last
  end
  
  def fb_profile_pic_square
    "http://graph.facebook.com/#{fb_username}/picture?type=square"
  end
  
  def fb_profile_pic_small
    "http://graph.facebook.com/#{fb_username}/picture?type=small"
  end
  
  def fb_profile_pic_normal
    "http://graph.facebook.com/#{fb_username}/picture?type=normal"
  end
  
  def fb_profile_pic_large
    "http://graph.facebook.com/#{fb_username}/picture?type=large"
  end
  
  def main_address
    addresses.first
  end
  
  protected
  
  def get_names_of_self_and_parents(o, org = nil)
    return [] if o.nil?
    names = ["#{o.name}"] if o.instance_of? Office
    names = ["#{o.parent.type_of_children unless o.ancestry.nil?} #{o.name}"] if o.instance_of? Organization
    
    if o.ancestry == nil || ( org.id == o.id if org)
      return ["#{o.name}"] if o.instance_of? Office
      return [] if o.instance_of? Organization
    else
      names += org ? get_names_of_self_and_parents(o.parent, org) : get_names_of_self_and_parents(o.parent)
    end
    
    names
  end
  
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  before_filter :get_parent_offices, only: [:index, :create, :edit]
  before_filter :get_orgs, only: [:index, :edit, :create]
  
  
  def index
    @person = Person.new
    @people = Person.joins(:organization).where('organization_id = ? OR organizations.ancestry ~ ?', current_organization.id, "^#{current_organization.id}$|^#{current_organization.id}/|/#{current_organization.id}/|/#{current_organization.id}$")

    if params[:commit] == I18n.t('general.search')
      filter 
    else
      @q = @people.search(params[:search])
    end
    
    @people = @q.page(params[:page]).per(20)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people.to_json(:include => [:addresses]) }
      format.js
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.js
        format.json { render json: @person, status: :created, location: @person }
      else
        format.js
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])
    @person.delete_offices
    @person.delete_addresses
    @person.delete_phone_numbers

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.js
      format.json { head :no_content }
    end
  end
  
  protected
  
  def filter
    @q = @people.where(cfo_id: Cfo.all.collect(&:id))
  
    unless params[:cfo_id].blank?
      @q = @q.where(cfo_id: params[:cfo_id])
    end
    unless params[:office_id].blank?
      @q = @q.joins(:people_offices).joins(:offices).where('people_offices.office_id = ? OR offices.ancestry ~ ?', params[:office_id], "^#{params[:office_id]}$|^#{params[:office_id]}/|/#{params[:office_id]}/|/#{params[:office_id]}$").uniq # ^a/  /a/  /a$   '^3/|/44/|/6$';
    end
    
    @q = @q.search(params[:search])
  end
  
  def get_orgs
    @organizations = current_organization.children
  end
  
  def get_parent_offices
    @offices = Office.roots
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_add_person.html.erb
<div id="add_person_form">
  <% url = params[:action] == 'edit' ? person_path : people_path
     method = params[:action] == 'edit' ? :put : :post
     remote = params[:action] == 'edit' ? false  : true
   %>

  <%= form_for person, url: url, method: method, remote: remote do |f| %>
    <% if flash[:error] %>
      <div class="flash error"><%= raw flash[:error] %></div>
    <% end %>
    <%= hidden_field_tag :add_another %>
    <%= render 'people/person_form', person: person %>
    
    <br/>

    <%= submit_tag t('general.save_and_add'), class: 'save_and_more save' unless params[:action] == 'edit' %>
    <%= submit_tag t('general.save'), class: 'save_and_close save', id: "save" %>
    <% if params[:action] == "edit" %>
      <%= link_to(t('.delete'), person_path(@person), method: :delete, class: 'delete cleangray', data: { confirm: t('.delete_confirm', person: @person.name) })%>
    <% end %>
  <% end %>
  
</div>

app/views/people/_addresses_fields.html.erb
<div id="address_fields">
  <% if person.new_record? || person.addresses.blank?%>
    <div id="addresses[0]">
      <%= "Primary" %><br>
      <%= text_area_tag "person[addresses_attributes][0][address]", nil, class: "entry" %>
      <%= hidden_field_tag "person[addresses_attributes][0][longitude]" %>
      <%= hidden_field_tag "person[addresses_attributes][0][latitude]" %>
    </div>
  <% else %>
    <% person.addresses.each_with_index do |address, index| %>
      <div id="addresses[<%= index %>]">
        <%= "Primary" if index == 0%><br>
        <%= text_area_tag "person[addresses_attributes][#{index}][address]", address.address, class: "entry"  %>
        <%= hidden_field_tag "person[addresses_attributes][#{index}][longitude]" %>
        <%= hidden_field_tag "person[addresses_attributes][#{index}][latitude]" %>
        <%= link_to '×', '#', class: 'delete_entry' unless index == 0 %>
      </div>
    <% end %>
  <% end %>
</div>
<%= link_to image_tag("add.png") + t('.add_an_address'), '#', id: 'add_an_address' %>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :middle_name %><br />
    <%= f.text_field :middle_name %>
  </div>
  <div class="field">
    <%= f.label :office_id %><br />
    <%= f.number_field :office_id %>
  </div>
  <div class="field">
    <%= f.label :organization_id %><br />
    <%= f.number_field :organization_id %>
  </div>
  <div class="field">
    <%= f.label :birth_date %><br />
    <%= f.text_field :birth_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/_menu.html.erb
<ul class="pillmenu">
  <li><%= link_to(t('.add_person'), '#', class: 'add_person', id: 'contacts_add_button') %></li>
  <li><%= link_to(t('.see_map'), '#', class: 'see_map', id: 'see_map_button') %></li>
  <li><%= link_to(t('.search_and_fiter'), '#', class: 'search_and_filter', id: 'search_and_filter_button') %></li>
</ul>

app/views/people/_offices_fields.html.erb
<div class="sfield office_field">
  <div id="office_selects">
    <% if person.new_record? || person.offices.blank?%>
      <div>
        <div id="office_select[0]" class="office_select">
          <%= select_tag "person[people_offices_attributes][0][office_id]", options_from_collection_for_select(@offices, :id, :name), include_blank: true, data_level: 0 %>
        </div>
      </div>
    <% else %>
      <% person.offices.each_with_index do |office, index| %>
        <div>
          <div id="office_select[<%= index %>]">
            <% ancestor_no = office.ancestors.count %>
            <% office.ancestors.each_with_index do |ancestor, index| %>
                <%= select_tag nil, options_from_collection_for_select(ancestor.siblings, :id, :name, ancestor.id), include_blank: true, data_level: index %>
            <% end %>
            
            <%= select_tag "person[people_offices_attributes][#{index}][office_id]", options_from_collection_for_select(office.siblings, :id, :name, office.id), include_blank: true, data_level: ancestor_no %>
          
          </div>
          <%= link_to '×', '#', class: 'delete_entry' unless index == 0 %>
        </div>
        
      <% end %>
      
    <% end %>
  </div>
  <%= link_to image_tag("add.png") + t('.add_an_office'), '#', id: 'add_an_office' %>
</div>

app/views/people/_organization_fields.html.erb
<div class="sfield organization_field">
  <div id="organization_selects">
    <% if person.new_record? || person.organization.nil? %>
      <%= select_tag "person[organization_id]", options_from_collection_for_select(@organizations, :id, :name), include_blank: true, data_level: 0 %><br>
    <% else %>
      <% ancestor_no = person.organization.ancestors.count %>
      <% person.organization.ancestors_up_to_current_organization(current_organization).each_with_index do |ancestor, index| %>
        <% unless ancestor.ancestry.nil? %>
          <%= select_tag nil, options_from_collection_for_select(ancestor.siblings, :id, :name, ancestor.id), include_blank: true, data_level: index-1 %>
        <% end %>
      <% end %>
        <%= select_tag "person[organization_id]", options_from_collection_for_select(person.organization.siblings, :id, :name, person.organization.id), include_blank: true, data_level: ancestor_no %>
    <% end %>
  </div>
</div>

app/views/people/_people.html.erb
<tr id="table_header">
  <th><%= sort_link @q, :last_name, t('.last_name'), params, remote: true %></th>
  <th><%= sort_link @q, :first_name, t('.first_name'), params, remote: true %></th>
  <th><%= sort_link @q, :middle_name, t('.middle_name'), params, remote: true %></th>
  <th><%= t('.offices') %></th>
  <th><%= t('.organizations') %></th>
  <th><%= t('.cfo') %></th>
  <th></th>
</tr>

<% people.each do |person| %>
  <%= render 'people/person', person: person %>
<% end %>

app/views/people/_person.html.erb
<tr id="<%= dom_id(person) %>" data-id="<%= person.id %>" class="person_row <%= extra if defined?(extra) %>" data-name="<%= person.name %>">
  <td class="last_name"><%= person.last_name %></td>
  <td class="first_name"><%= person.first_name %></td>
  <td class="first_name"><%= person.middle_name %></td>
  <td class="offices">
  <% person.office_names.each do |office_name| %>
    <span class="office_name"><%= office_name %></span>
  <% end %> 
  </td>
  <td class="organization">
    <span class="organization_name">
      <%= person.organization_names(current_organization) %>
    </span>
  </td>
  <td><%= person.cfo.name if person.cfo %></td>
</tr>

app/views/people/_person_form.html.erb
<% if params[:action] == "edit" %>
  <script type="text/javascript">

  function updateMarkerPosition(latLng) {
    document.getElementById('person_addresses_attributes_0_longitude').value = latLng.lng()
    document.getElementById('person_addresses_attributes_0_latitude').value = latLng.lat()
  }

  function updateMarkerAddress(str) {
    document.getElementById('address').innerHTML = str;
  }

  function initialize() {
    
    <%
      if person.new_record? || (person.addresses.first.latitude.blank? && person.addresses.first.longitude.blank?)
        lat_long = @person.organization.latitude_longitude
      else
        address = person.addresses.first
        lat_long = [address.latitude, address.longitude] 
      end
      
      lat = lat_long[0]
      long = lat_long[1]
    %>

    var latLng = new google.maps.LatLng(<%= lat %>, <%= long %>);
    var map = new google.maps.Map(document.getElementById('map_canvas_edit'), {
      zoom: 17,
      center: latLng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });
    var marker = new google.maps.Marker({
      position: latLng,
      title: 'Point A',
      map: map,
      draggable: true
    });
    
    // Update current position info.
    updateMarkerPosition(latLng);
    
    google.maps.event.addListener(marker, 'drag', function() {
      updateMarkerPosition(marker.getPosition());
    });
  }

  // Onload handler to fire off the app.
  google.maps.event.addDomListener(window, 'load', initialize);
  </script>

  <div id="map_canvas_edit"></div>
<% end %>

<%= fields_for person, {validators: {}} do |pf| %>
<div class="customform contact_form">
  <div class="field_group">
    <div class="sfield">
      <div class="ls"><%= pf.label :last_name, t('people.index.last_name') %>:</div>
      <div class="rs"><%= pf.text_field :last_name %></div>
    </div>
    <div class="sfield">
      <div class="ls"><%= pf.label :first_name, t('people.index.first_name') %>:</div>
      <div class="rs"><%= pf.text_field :first_name %></div>
    </div>
    <div class="sfield">
      <div class="ls"><%= pf.label :middle_name, t('people.index.middle_name') %>:</div>
      <div class="rs"><%= pf.text_field :middle_name %></div>
    </div>
  </div>
  
  <div class="sfield field_group">
    <div class="ls"><%= pf.label :fb_profile, t('people.index.facebook_profile') %>:</div>
    <div class="rs"><%= pf.text_field :fb_profile %></div>
  </div>
  
  
  <div class="sfield field_group">
    <div class="ls"><%= t('.addresses')%></div>
    <div class="rs">
      <%= render 'people/addresses_fields', no_remove: true, person: person %>
    </div>
  </div>
  
  <div class="sfield field_group">
    <div class="ls"><%= t('.phone_numbers')%></div>
    <div class="rs">
      <%= render 'people/phone_numbers_fields', no_remove: true, person: person %>
    </div>
  </div>
  
  <div class="sfield field_group">
    <div class="ls"><%= t('.offices')%></div>
    <div class="rs">
      <%= render 'people/offices_fields', no_remove: true, person: person %>
    </div>
  </div>
  
  <div class="sfield field_group">
    <div class="ls"><%= t('.cfo')%></div>
    <div class="rs">
      <% Cfo.all.each do |cfo| %>
        <%= pf.radio_button :cfo_id, cfo.id %>
        <%= pf.label :name, cfo.name %>
        <br>
      <% end %>
    </div>
  </div>
  
  <div class="sfield field_group">
    <div class="ls"><%= t('.organization')%></div>
    <div class="rs">
      <%= render 'people/organization_fields', no_remove: true, person: person %>
    </div>
  </div>
</div>
  
<% end %>

app/views/people/_phone_numbers_fields.html.erb
<div id="phone_number_fields">
    <% if person.new_record? || person.phone_numbers.blank?%>
      <div id="phone_numbers[0]">
        <%= text_field_tag "person[phone_numbers_attributes][0][phone_number]" %>
      </div>
    <% else %>
      <% person.phone_numbers.each_with_index do |phone_number, index| %>
        <div id="phone_numbers[<%= index %>]">
          <%= text_field_tag "person[phone_numbers_attributes][#{index}][phone_number]", phone_number.phone_number %>
          <%= link_to '×', '#', class: 'delete_entry' unless index == 0 %>
        </div>
      <% end %>
    <% end %>
</div>
<%= link_to image_tag("add.png") + t('.add_a_phone_number'), '#', id: 'add_a_phone_number' %>

app/views/people/create.js.erb
$('#table_header').after("<%= j(render('person', person: @person)) %>")
<% unless params[:add_another] == 'true' %>
  $('#add_person_div').dialog('destroy')
<% end %>
$('#<%= dom_id(@person) %>').effect('highlight')
$('#add_person_div').html('<%= j(render('add_person', person: Person.new)) %>')

app/views/people/edit.html.erb
<h1>Editing <%= @person.name %><small> <%= link_to 'Profile', @person %></small></h1>

<!--
<div id="fb_profile_pic">
  <%#= image_tag @person.fb_profile_pic_large %>
</div>
-->

<%= render 'add_person', person: @person %>

app/views/people/index.html.erb
<div class="pagemenu">
  <%= render partial: 'menu' %>
</div>

<div id="canvas">
  <div id="map" style="<%= 'display:none' %>">
  </div>
  <div id="table">
    <table class="listing" cellpadding="0" cellspacing="0">
      <tbody id="people_table">
        <%= render 'people/people', people: @people %>
        
      </tbody>
    </table>
    
  </div>
</div>

<div id="add_person_div" style="display:none" title="<%= t('.add_person') %>" class="fingerme">
  <%= render 'add_person', person: @person %>
</div>

app/views/people/index.js.erb
markers = []

function initialize() {
  var myLatlng = new google.maps.LatLng(14.445282806398495, 120.98913688280334);
  var mapOptions = {
    zoom: 15,
    center: myLatlng,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  }
  var map = new google.maps.Map(document.getElementById('map'), mapOptions);
  
  <% @people.each_with_index do |person, index| %>
    <% if person.main_address.has_latlng? %>
      latlng = new google.maps.LatLng(<%= person.addresses.first.latitude %>,<%= person.addresses.first.longitude %>);
      marker = new google.maps.Marker({
        position: latlng,
        map: map,
        title: '<%= person.name %>',
        labelContent: '<%= person.name %>',
        html: '<div><%= image_tag person.fb_profile_pic_square unless person.fb_profile.blank? %><%= link_to person.name, person_path(person) %><br><%= person.organization_names(current_organization) %></div>'
      });
      markers.push(marker)
    <% end %>
  <% end %>
  
  for (var i = 0; i < markers.length; i++) {
    var marker = markers[i];
    var infowindow = new google.maps.InfoWindow();
    
    google.maps.event.addListener(marker, 'click', function () {
      infowindow.setContent(this.html);
      infowindow.open(map, this);
    });
  }
}

initialize();

$('#people_table').html('<%= j(render('people', people: @people)) %>')