config/routes.rb
Mtp::Application.routes.draw do
  resources :people

  resources :organizations do
    collection do
      get :get_children
    end
    
    member do
      get :set_current
    end
  end
  
  resources :offices do
    collection do
      get :get_children
      get :get_roots
    end
  end
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"

  root :to => "sessions#new"
  
  resources :users
  resources :sessions

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :name, :ancestry, :longitude, :latitude, :address
  attr_accessible :type_of_children
  attr_accessible :parent_id
  
  acts_as_tree
  
  has_many :people, :dependent => :destroy
  has_many :users
  validates_presence_of :name, message: "can't be blank"
  
  def ancestors_up_to_current_organization(org)    
    organizations = []
    
    ancestry.split('/').reverse.each do |org_id|
      return organizations.reverse if org.id.to_s == org_id
      organizations << Organization.find(org_id)
    end
    
    organizations.reverse
  end
  
  def latitude_longitude
    if longitude == nil && latitude == nil
      ancestry.split('/').reverse.each do |ancestor_id|
        ancestor = Organization.find(ancestor_id)
        if ancestor.longitude != nil && ancestor.latitude != nil
          return [ancestor.latitude, ancestor.longitude]
        end
      end
    else
      [latitude ,longitude]
    end
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # GET /organizations
  # GET /organizations.json
  before_filter :get_root_organization, only: [:index]
  
  def index
    @organizations = @root_org.children
    @organization = Organization.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    begin
      @organization = Organization.find params[:id]
    rescue ActiveRecord::RecordNotFound => e
      @organization = nil
    end

    respond_to do |format|
      format.js
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(params[:organization])
    @parent = Organization.find(params[:organization][:parent_id])

    respond_to do |format|
      if @organization.save
        format.js
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.js
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to organizations_path, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def get_children
    @organizations = Organization.find(params[:id]).children
    
    respond_to do |format|
      format.json { render json: @organizations }
      format.js # new.html.erb
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy
    

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end
  
  def set_current
    session[:current_organization_id] = params[:id]
    redirect_to people_url
  end
  
  protected
  
  def get_root_organization
    @root_org = Organization.first
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_add_org.html.erb
<div id="add_org_form">
  <%= form_for organization, url: organizations_path, method: :post, remote: true, validate: true do |f| %>
    <% if flash[:error] %>
      <div class="flash error"><%= raw flash[:error] %></div>
    <% end %>
    <%= f.hidden_field :parent_id %>
    <%= hidden_field_tag :add_another %>
    <div class="customform">
      <div class="sfield">
        <div class="ls">
          <%= f.label :name %>
        </div>
        <div class="rs">
          <%= f.text_field :name %>
        </div>
      </div>
      <div class="sfield">
        <div class="ls">
          <%= f.label :type_of_children %>
        </div>
        <div class="rs">
          <%= f.text_field :type_of_children %>
        </div>
      </div>
      <div class="ls"></div>
    </div>
    <%= submit_tag t('general.save_and_close'), class: 'save_and_close save' %>
    <%= submit_tag t('general.save_and_add'), class: 'save_and_more save' %>
  <% end %>
</div>

app/views/organizations/_form.html.erb
<script type="text/javascript">
  function updateMarkerAddress(str) {
    document.getElementById('address').innerHTML = str;
  }

  function initialize() {
    <% lat_long = @organization.latitude_longitude %>
    <% lat = lat_long[0] %>
    <% long = lat_long[1] %>

    var latLng = new google.maps.LatLng(<%= lat %>, <%= long %>);
    var map = new google.maps.Map(document.getElementById('map_canvas_organization_edit'), {
      zoom: 17,
      center: latLng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });
    var marker = new google.maps.Marker({
      position: latLng,
      title: 'Point A',
      map: map,
      draggable: true
    });
    
    // Update current position info.
    updateMarkerPosition(latLng);
    
    google.maps.event.addListener(marker, 'drag', function() {
      updateMarkerPosition(marker.getPosition());
    });
    
  }

  function updateMarkerPosition(latLng) {
    document.getElementById('organization_latitude').value = latLng.lat()
    document.getElementById('organization_longitude').value = latLng.lng()
  }


  // Onload handler to fire off the app.
  google.maps.event.addDomListener(window, 'load', initialize);

</script>

<div id="map_canvas_organization_edit" style="width:100%; height: 300px;"></div>

<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field_group">
    <div class="sfield">
      <div class="ls"><%= f.label :name %>:</div>
      <div class="rs"><%= f.text_field :name %></div>
    </div>
    <div class="sfield">
      <div class="ls"><%= f.label :type_of_children %>:</div>
      <div class="rs"><%= f.text_field :type_of_children %></div>
    </div>
    <div class="sfield">
      <div class="ls"><%= f.label :address %>:</div>
      <div class="rs"><%= f.text_area :address, size: 30 %></div>
    </div>
  </div>
  
  <%= f.hidden_field :longitude %>
  <%= f.hidden_field :latitude %>
  
  <div class="item formactions">
    <%= f.submit %><%= link_to(t('.back'), :back, :class=> "cancel")%>
  </div>
  
  <div class="formactions dangerzone">
    <h3><%= t('.danger_zone') %></h3>
    <div class="content">
    <p><%= t('.danger_explanation') %></p>
    <hr/>
    <p style="margin-top: 15px;"><%= link_to(t('.delete'), organization_path(@organization), method: :delete, class: 'delete cleangray', data: { confirm: t('.delete_confirm', type: @organization.parent.type_of_children) })%></p>
    </div>
  </div>
<% end %>

app/views/organizations/_org.html.erb
<li><%= link_to(org.name, organization_path(org), remote: true, class: 'org_link', data: {id: org.id}) %> <span class="ctrl"><%= link_to(t('general.edit'), edit_organization_path(org)) %></span></li>

app/views/organizations/_org_column.html.erb
<% has_children = parent.children.count > 0 %>
<div class="org_column" id="<%= dom_id(parent) %>" data-level="<%= parent.ancestry.to_s.split('/').length %>">
  <a class="org_new add_sub_org" href="#" data-parent-id="<%= parent.id %>">+ <%= t('organizations.index.add_a_sub_org', type_of_children: parent.type_of_children) %></a>
  <ul>
    <% parent.children.order('name').each do |org| %>
      <%= render 'org', org: org %>
    <% end %>
    <% unless has_children %>
      <li><a class="org_big_add add_sub_org" data-parent-id="<%= parent.id %>" href="#"><span class="plus">+</span><span><%= t('organizations.index.add_a_sub_org', type_of_children: parent.type_of_children) %></span></a> </li>
    <% end %>
  </ul>
</div>

app/views/organizations/add_org.js.erb
$('#new_org').html('<%= j(render('add_org', organization: @organization)) %>')

app/views/organizations/create.js.erb
$('#<%= dom_id(@parent) %> ul').prepend('<%= j(render('org', org: @organization)) %>')
<% unless params[:add_another] == 'true' %>
	$('#new_org').dialog('destroy')
<% end %>
$('[data-id=<%= @organization.id %>]').effect('highlight')
$('.org_big_add').closest('li').hide()
$('#new_org').html('<%= j(render('add_org', organization: @parent.children.new)) %>')

app/views/organizations/edit.html.erb
<h1>Editing <%= @organization.parent.type_of_children %> <%= @organization.name %></h1>

<%= render 'form' %>

app/views/organizations/index.html.erb
<div class="index carea">

  <div class="titlebar">
    <h1>Organizations</h1>
    <p>From this screen you can edit, delete or rearrange your organizations. Clicking "Add new organization"<br/>will do a quick add by name. To edit more details, permissions and other info, select "edit" from the item's<br/>name on the list.</p>
  </div>
  
  <h2><%= current_organization.name %></h2>
  
  <% if current_organization.children.length == 0 %>
    <br/><%= link_to(t('.add_sub_org', type_of_children: @root_org.type_of_children.pluralize), '#', id: 'add_sub_orgs') %>
  <% end %>
  <div class="orgwrap">
  <div id="orgs" style="<%= 'display:none' if current_organization.children.length == 0 %>">
    <%= render 'org_column', parent: current_organization %>
    <div class="org_column" id="spinner_column" style="display:none">
      <a class="org_new">+ </a>
      <ul>
        <li><%= image_tag('spinner.gif') %></li>
      </ul>
    </div>
  </div>
  </div>

</div>

<div id="new_org" style="display:none" title="<%= t('.add_sub_org') %>" class="fingerme">
  <%= render 'add_org', organization: @organization %>
</div>

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @organization.name %>
</p>


<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/show.js.erb
$('#spinner_column').hide()
if($('#<%= dom_id(@organization) %>')[0]) {
  $('#<%= dom_id(@organization) %>').replaceWith('<%= j(render('org_column', parent: @organization)) %>')
  $('#<%= dom_id(@organization) %>').show()
} else {
  $('#spinner_column').before('<%= j(render('org_column', parent: @organization)) %>')
}