config/routes.rb
Mtp::Application.routes.draw do
  resources :people

  resources :organizations do
    collection do
      get :get_children
    end
    
    member do
      get :set_current
    end
  end
  
  resources :offices do
    collection do
      get :get_children
      get :get_roots
    end
  end
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"

  root :to => "sessions#new"
  
  resources :users
  resources :sessions

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Finder</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%#= javascript_include_tag params[:controller] %>
  <%= csrf_meta_tags %>
  
  <%= javascript_include_tag "i18n" %>
  <%= javascript_tag do %>
    I18n.defaultLocale = "<%= I18n.default_locale %>";
    I18n.locale = "<%= I18n.locale %>";
  <% end %>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" type="text/javascript"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.js" type="text/javascript"></script>
  
  <link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>
  
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
</head>
<body id="<%= controller.controller_name %>_controller" class="<%= params[:action] %>">
  
  
  
    <div id="outer">
      <% if current_user %>
        <div id="menutoptop">
          <%= render 'shared/nav' %>
        </div>
        
        <div id="menutop">
          <div id="menus">
              <span>
                <%#= link_to image_tag("finder_logo.png"), people_path, id: "finder_logo" %>
              </span>
            <div id="menus_container">
              
            
              <span class="<%= params[:controller] == "people" ? 'main_link_clicked' : 'main_link' %>">
                <%= link_to 'People', people_path %>
              </span>
              <span class="<%= params[:controller] == "organizations" ? 'main_link_clicked' : 'main_link' %>">
                <%= link_to 'Organizations', organizations_path %>
              </span>
            </div>
          </div>
        </div>
        
        <%
          container_id = 
            if params[:controller] == "organizations" &&  params[:action] == "edit"
              "organization_edit_container"
            elsif params[:controller] == "people" &&  params[:action] == "show"
              "people_show_container"
            else
              "container"
            end
        %>
        
        
        <div id="<%= container_id %>">
          <div id="left" style="<%= 'display:none' if params[:controller] != "people" || params[:action] != 'index'%>" >
            <%= render 'people/left_panel' if params[:controller] == "people" && params[:action] == 'index' %>
          </div>
          <div id=<%= "main" unless params[:controller] == "organizations" || params[:action] == 'show' || params[:action] == 'edit' %>>
            <%= yield %>
            
          </div>
        </div>
      <% else %>
  
          
            <%= yield %>
          
    
      <% end %>
    <div class="footer">
      <%= render 'shared/footer' %>
    </div>
  </div>

</body>
</html>